fix: ci 2.25 add debug

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -159,18 +159,18 @@ jobs:
         with:
           target: 'http://localhost:8089'
           docker_name: 'ghcr.io/zaproxy/zaproxy:stable'
-          report_name: 'zap-report'
+          cmd_options: '-a -r zap-report.html'
 
 
-      - name: 🔍 List after ZAP scan
-        run: ls -lah
+      - name: 🔍 Debug – list zap/wrk files
+        run: ls -lah zap/wrk || echo "zap/wrk not found"
 
 
-      - name:  Upload ZAP HTML Report (Artifact)
+      - name: 📤 Upload ZAP report
         uses: actions/upload-artifact@v4
         with:
           name: zap-security-report
-          path:  zap-report.html
+          path: zap/wrk/zap-report.html
 
 
 
